# -*- coding: utf-8 -*-
"""nan assigments.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14hvDOmE_7Gh6fuscrIuGVBqUswIn9uvG
"""

import pandas as pd
import numpy as np

df = pd.DataFrame({
    "age": [25, "unknown", 30, "NA", 40],
    "salary": ["5000", "N/A", "?", "7000", "not reported"],
    "city": ["Riyadh", "Jeddah", "unknown", "Dammam", "Riyadh"]
})
""" task 1 """

miising = ["unknown", "N/A", "NA", "?" , "not reported"]

""" task 2 """

df.replace(miising, np.nan, inplace=True)
df

df.isna().mean()
""" task 3 """
"""salary because its numbers and the model will not be able to calculate within the best accuracy cuz there isnt that much of data"""
